window.BibliotecaPreguntas = {
  fase0: [
    { pregunta: "¿Quién es el autor de El Quijote?", opciones: ["Miguel de Cervantes", "Lope de Vega", "Calderón de la Barca", "Garcilaso de la Vega"], correcta: 0 },
    { pregunta: "¿Cómo se titula la primera parte de El Quijote publicada en 1605?", opciones: ["El ingenioso hidalgo don Quijote de la Mancha", "El ingenioso caballero don Quijote de la Mancha", "Don Quijote de la Mancha", "Las aventuras de don Quijote"], correcta: 0 },
    { pregunta: "¿En qué año se publica la primera parte de El Quijote?", opciones: ["1605", "1615", "1613", "1600"], correcta: 0 },
    { pregunta: "¿En qué año se publica la segunda parte de El Quijote?", opciones: ["1615", "1605", "1617", "1613"], correcta: 0 },
    { pregunta: "¿Qué género literario parodia El Quijote?", opciones: ["Libros de caballerías", "Novela pastoril", "Novela picaresca", "Novela bizantina"], correcta: 0 },
    { pregunta: "¿Cómo se llama el protagonista de la obra?", opciones: ["Don Quijote", "Sancho Panza", "Sansón Carrasco", "Rocinante"], correcta: 0 },
    { pregunta: "¿Cómo se llama el escudero de don Quijote?", opciones: ["Sancho Panza", "Ginés de Pasamonte", "El bachiller", "El ventero"], correcta: 0 },
    { pregunta: "¿Qué provoca la locura de don Quijote?", opciones: ["La lectura de libros de caballerías", "Un hechizo", "Un golpe", "Una enfermedad"], correcta: 0 },
    { pregunta: "¿Cómo se llama la dama idealizada por don Quijote?", opciones: ["Dulcinea del Toboso", "Aldonza Panza", "Marcela", "Dorotea"], correcta: 0 },
    { pregunta: "¿Cuál es el nombre real de Dulcinea según la obra?", opciones: ["Aldonza Lorenzo", "Aldonza Panza", "Leonor López", "Catalina Salazar"], correcta: 0 },
    { pregunta: "¿Cuántas partes tiene El Quijote?", opciones: ["Dos", "Tres", "Una", "Cuatro"], correcta: 0 },
    { pregunta: "¿Cuántas salidas realiza don Quijote a lo largo de la obra?", opciones: ["Tres", "Dos", "Cuatro", "Una"], correcta: 0 },
    { pregunta: "¿Qué animal monta don Quijote?", opciones: ["Un caballo", "Un burro", "Un mulo", "Un asno"], correcta: 0 },
    { pregunta: "¿Qué episodio famoso confunde gigantes con molinos?", opciones: ["Los molinos de viento", "Los galeotes", "La venta", "Los batanes"], correcta: 0 },
    { pregunta: "¿Cómo termina la historia de don Quijote?", opciones: ["Recupera la cordura y muere", "Muere loco", "Se convierte en caballero famoso", "Desaparece"], correcta: 0 }
  ],

  fase1: [
    { pregunta: "¿Qué título recibe la segunda parte de la obra publicada en 1615?", opciones: ["El ingenioso caballero don Quijote de la Mancha", "El ingenioso hidalgo don Quijote de la Mancha", "Segunda parte de Don Quijote", "Las nuevas aventuras de don Quijote"], correcta: 0 },
    { pregunta: "¿Qué hecho motiva la publicación de la segunda parte auténtica?", opciones: ["La aparición de una segunda parte apócrifa", "El fracaso de la primera", "Una petición del rey", "Un cambio de género"], correcta: 0 },
    { pregunta: "¿Quién firma la segunda parte apócrifa de El Quijote?", opciones: ["Alonso Fernández de Avellaneda", "Lope de Vega", "Mateo Alemán", "Quevedo"], correcta: 0 },
    { pregunta: "¿Dónde se publica la obra apócrifa de Avellaneda?", opciones: ["Tarragona", "Madrid", "Valencia", "Sevilla"], correcta: 0 },
    { pregunta: "¿Cómo se presenta don Quijote en la obra de Avellaneda?", opciones: ["Como un loco vulgar e incoherente", "Como héroe ideal", "Como sabio moral", "Como caballero prudente"], correcta: 0 },
    { pregunta: "¿Qué rasgo destaca del Sancho de Avellaneda?", opciones: ["Es un glotón sin ingenio", "Es prudente y sabio", "Es noble", "Es caballeresco"], correcta: 0 },
    { pregunta: "¿Qué estructura general presentan las aventuras de El Quijote?", opciones: ["Un modelo itinerante", "Una unidad de lugar", "Una estructura epistolar", "Un relato circular cerrado"], correcta: 0 },
    { pregunta: "¿Qué volumen contiene las dos primeras salidas?", opciones: ["El de 1605", "El de 1615", "El apócrifo", "El de 1613"], correcta: 0 },
    { pregunta: "¿Quién arma caballero a don Quijote?", opciones: ["El ventero", "Un duque", "Un caballero andante", "El cura"], correcta: 0 },
    { pregunta: "¿Qué personaje acompaña a don Quijote desde la segunda salida?", opciones: ["Sancho Panza", "El barbero", "El bachiller", "Ginés"], correcta: 0 },
    { pregunta: "¿Qué episodio pertenece a la primera salida?", opciones: ["La defensa del muchacho Andrés", "Los molinos de viento", "La cueva de Montesinos", "Los leones"], correcta: 0 },
    { pregunta: "¿Qué episodio pertenece a la segunda salida?", opciones: ["Los molinos de viento", "La Blanca Luna", "El palacio ducal", "La muerte final"], correcta: 0 },
    { pregunta: "¿Quién es Sansón Carrasco?", opciones: ["Un bachiller que intenta curar a don Quijote", "Un duque", "Un ventero", "Un galeote"], correcta: 0 },
    { pregunta: "¿Con qué nombre se disfraza Sansón Carrasco en su primer enfrentamiento?", opciones: ["Caballero de los Espejos", "Caballero de la Blanca Luna", "Caballero del Verde Gabán", "Caballero del Bosque"], correcta: 0 },
    { pregunta: "¿Con qué nombre derrota finalmente a don Quijote?", opciones: ["Caballero de la Blanca Luna", "Caballero de los Espejos", "Caballero del Sol", "Caballero del León"], correcta: 0 },
    { pregunta: "¿Qué consecuencia tiene la derrota final de don Quijote?", opciones: ["El regreso a su aldea", "Una nueva salida", "Su encarcelamiento", "Su fama universal"], correcta: 0 },
    { pregunta: "¿Qué tipo de historias se intercalan en la novela?", opciones: ["Pastoriles, amorosas y moriscas", "Solo caballerescas", "Solo picarescas", "Solo históricas"], correcta: 0 },
    { pregunta: "¿Cómo se relacionan las historias interpoladas en la segunda parte?", opciones: ["De forma más estrecha con la trama principal", "De manera independiente", "No aparecen", "Rompen la narración"], correcta: 0 },
    { pregunta: "¿Qué rasgo define a Sancho Panza?", opciones: ["Inculto pero no tonto", "Sabio erudito", "Loco como su amo", "Cruel"], correcta: 0 },
    { pregunta: "¿Dónde demuestra Sancho su capacidad de gobierno?", opciones: ["En Barataria", "En La Mancha", "En Sevilla", "En Barcelona"], correcta: 0 },
    { pregunta: "¿Qué función tiene Dulcinea en la obra?", opciones: ["Ser el motor ideal de las hazañas", "Actuar como narradora", "Ser antagonista", "Gobernar Barataria"], correcta: 0 },
    { pregunta: "¿Qué contraste genera Dulcinea?", opciones: ["Idealización frente a realidad", "Riqueza frente a pobreza", "Campo frente a ciudad", "Pasado frente a futuro"], correcta: 0 },
    { pregunta: "¿Qué tipo de narrador aparece al inicio?", opciones: ["Omnisciente", "Protagonista", "Testigo", "Epistolar"], correcta: 0 },
    { pregunta: "¿Qué personaje aparece como supuesto autor de la historia?", opciones: ["Cide Hamete Benengeli", "Avellaneda", "Sancho Panza", "El cura"], correcta: 0 },
    { pregunta: "¿Qué recurso narrativo se produce cuando los personajes conocen el libro?", opciones: ["Un juego de niveles de ficción", "Una narración lineal", "Un cambio de género", "Un final abierto"], correcta: 0 },
    { pregunta: "¿Qué tono predomina en la obra de Avellaneda?", opciones: ["Escatológico", "Trágico", "Heroico", "Lírico"], correcta: 0 },
    { pregunta: "¿Qué intención declara Cervantes al inicio de El Quijote?", opciones: ["Parodiar los libros de caballerías", "Exaltar la caballería", "Imitar la épica clásica", "Escribir una crónica histórica"], correcta: 0 },
    { pregunta: "¿Qué efecto tuvo la publicación de El Quijote?", opciones: ["Gran popularidad inmediata", "Fracaso inicial", "Censura", "Olvido"], correcta: 0 },
    { pregunta: "¿Qué imagen global ofrece la obra de la sociedad?", opciones: ["Variada y satírica", "Idealizada", "Trágica", "Heroica"], correcta: 0 }
  ],

  fase2: [
    { pregunta: "¿Qué relación establece El Quijote entre locura y justicia?", opciones: ["La locura impulsa ideales justos", "La locura elimina la moral", "No existe relación", "La justicia es absurda"], correcta: 0 },
    { pregunta: "¿Cómo evoluciona don Quijote a lo largo de la obra?", opciones: ["Gana complejidad y hondura", "Se vuelve más simple", "Desaparece", "No evoluciona"], correcta: 0 },
    { pregunta: "¿Qué ocurre cuando don Quijote recupera la cordura?", opciones: ["Muere", "Vuelve a salir de aventuras", "Se casa", "Gobierna Barataria"], correcta: 0 },
    { pregunta: "¿Qué efecto suelen tener las acciones de don Quijote?", opciones: ["Resultados contrarios a los perseguidos", "Éxitos constantes", "Reconocimiento social", "Justicia efectiva"], correcta: 0 },
    { pregunta: "¿Qué permite el modelo itinerante de El Quijote?", opciones: ["Integrar episodios variados", "Reducir personajes", "Eliminar historias secundarias", "Unificar el estilo"], correcta: 0 },
    { pregunta: "¿Qué simboliza el episodio de los molinos?", opciones: ["La confusión entre realidad y ficción", "La victoria heroica", "La sátira política", "La crítica religiosa"], correcta: 0 },
    { pregunta: "¿Qué función cumplen los duques?", opciones: ["Burlarse de don Quijote y Sancho", "Curar a don Quijote", "Narrar la historia", "Representar al pueblo"], correcta: 0 },
    { pregunta: "¿Qué rasgo define la relación entre don Quijote y Sancho?", opciones: ["Contraste y evolución mutua", "Jerarquía rígida", "Antagonismo", "Indiferencia"], correcta: 0 },
    { pregunta: "¿Qué destaca del lenguaje de Sancho?", opciones: ["Su carácter popular y refranes", "Su estilo culto", "Su tono épico", "Su arcaísmo"], correcta: 0 },
    { pregunta: "¿Qué recurso predomina en la caracterización de personajes?", opciones: ["El diálogo", "La descripción épica", "El monólogo interior", "La narración epistolar"], correcta: 0 },
    { pregunta: "¿Qué efecto produce la parodia caballeresca?", opciones: ["Comicidad", "Tragedia", "Suspense", "Didactismo"], correcta: 0 },
    { pregunta: "¿Qué tipo de lenguaje se imita a veces en El Quijote?", opciones: ["El arcaico de los libros de caballerías", "El científico", "El jurídico", "El bíblico"], correcta: 0 },
    { pregunta: "¿Qué aporta la multiplicidad de registros lingüísticos?", opciones: ["Verosimilitud y decoro", "Uniformidad", "Rigidez formal", "Confusión"], correcta: 0 },
    { pregunta: "¿Qué función tienen las historias interpoladas?", opciones: ["Dar variedad y amenidad", "Romper la narración", "Eliminar la acción", "Cerrar la trama"], correcta: 0 },
    { pregunta: "¿Cómo se valora hoy la burla de Cervantes hacia don Quijote?", opciones: ["Combina burla y compasión", "Es cruel", "Es indiferente", "Es puramente trágica"], correcta: 0 },
    { pregunta: "¿Qué interpretación propone Hauser sobre don Quijote?", opciones: ["Metáfora del fracaso de una España arcaica", "Héroe épico clásico", "Figura religiosa", "Crónica histórica"], correcta: 0 },
    { pregunta: "¿Qué destacan Unamuno y Maeztu?", opciones: ["El heroísmo del personaje", "La sátira política", "La crítica social directa", "El realismo extremo"], correcta: 0 },
    { pregunta: "¿Qué caracteriza al final de la obra?", opciones: ["Coherencia con la evolución del protagonista", "Final abierto", "Castigo ejemplar", "Triunfo heroico"], correcta: 0 },
    { pregunta: "¿Qué aporta el juego de perspectivas narrativas?", opciones: ["Complejidad interpretativa", "Linealidad", "Simplicidad", "Didactismo"], correcta: 0 },
    { pregunta: "¿Qué convierte a El Quijote en una obra universal?", opciones: ["La profunda humanidad de sus personajes", "Su temática local", "Su estructura épica", "Su finalidad moral"], correcta: 0 },
    { pregunta: "¿Qué tensión recorre toda la obra?", opciones: ["Idealismo frente a realidad", "Campo frente a ciudad", "Bien frente a mal", "Pasado frente a futuro"], correcta: 0 },
    { pregunta: "¿Qué papel cumple la risa en El Quijote?", opciones: ["Instrumento crítico", "Elemento trágico", "Recurso menor", "Ausencia total"], correcta: 0 },
    { pregunta: "¿Qué demuestra el gobierno de Barataria?", opciones: ["La inteligencia práctica de Sancho", "La inutilidad del poder", "La corrupción política", "La sátira religiosa"], correcta: 0 },
    { pregunta: "¿Qué efecto produce la conciencia literaria de los personajes?", opciones: ["Modernidad narrativa", "Confusión innecesaria", "Pérdida de ritmo", "Moralización"], correcta: 0 },
    { pregunta: "¿Qué relación hay entre técnica narrativa y sentido global?", opciones: ["La técnica refuerza el significado", "La técnica es decorativa", "No hay relación", "La técnica contradice el sentido"], correcta: 0 },
    { pregunta: "¿Qué visión global ofrece Cervantes de su tiempo en El Quijote?", opciones: ["Crítica y humanizada", "Triunfalista", "Pesimista absoluta", "Idealizada"], correcta: 0 },
    { pregunta: "¿Qué logra Cervantes con el fracaso constante del héroe?", opciones: ["Humanizarlo", "Ridiculizarlo totalmente", "Condenarlo moralmente", "Eliminar su valor"], correcta: 0 },
    { pregunta: "¿Qué aporta la ambigüedad interpretativa?", opciones: ["Riqueza de lecturas", "Mensaje único", "Didactismo cerrado", "Confusión"], correcta: 0 },
    { pregunta: "¿Qué define a don Quijote como personaje?", opciones: ["Complejidad y hondura", "Simple comicidad", "Maldad", "Cobardía"], correcta: 0 },
    { pregunta: "¿Qué representa finalmente don Quijote?", opciones: ["La defensa idealista frente a la realidad", "El triunfo de la fantasía", "El poder político", "La sabiduría académica"], correcta: 0 },
    { pregunta: "¿Qué logra El Quijote como conjunto?", opciones: ["Una concepción nueva de la novela", "Una sátira aislada", "Un experimento fallido", "Una imitación caballeresca"], correcta: 0 }
  ],

  fase3: [
    { pregunta: "¿Por qué El Quijote se considera origen de la novela moderna?", opciones: ["Por su innovación técnica y perspectivística", "Por su temática épica", "Por su moral religiosa", "Por su estructura clásica"], correcta: 0 },
    { pregunta: "¿Qué función cumple Cide Hamete Benengeli en la obra?", opciones: ["Introducir un juego de perspectivas", "Cerrar la narración", "Moralizar el relato", "Sustituir al autor"], correcta: 0 },
    { pregunta: "¿Qué efecto tiene la metaficción en El Quijote?", opciones: ["Refuerza su modernidad", "Reduce la verosimilitud", "Elimina el humor", "Simplifica la lectura"], correcta: 0 },
    { pregunta: "¿Qué simboliza la muerte final de don Quijote?", opciones: ["El fin del ideal caballeresco", "El triunfo del héroe", "La redención religiosa", "La victoria social"], correcta: 0 },
    { pregunta: "¿Qué distingue esencialmente a Cervantes frente a Avellaneda?", opciones: ["La profundidad moral y narrativa", "El tema", "La extensión", "El número de personajes"], correcta: 0 },
    { pregunta: "¿Qué logra Cervantes con la combinación de burla y compasión?", opciones: ["Una visión humanista", "Una sátira cruel", "Un mensaje moral cerrado", "Un tono trágico"], correcta: 0 },
    { pregunta: "¿Qué papel juega el lector en El Quijote?", opciones: ["Activo e interpretativo", "Pasivo", "Guiado explícitamente", "Moralizado"], correcta: 0 },
    { pregunta: "¿Qué revela El Quijote sobre la ficción?", opciones: ["Su poder y sus límites", "Su inutilidad", "Su peligrosidad absoluta", "Su falsedad"], correcta: 0 },
    { pregunta: "¿Qué síntesis logra Cervantes al final de la obra?", opciones: ["Humor, crítica y humanidad", "Tragedia pura", "Épica heroica", "Didactismo"], correcta: 0 },
    { pregunta: "¿Qué define la grandeza universal de El Quijote?", opciones: ["La universalidad de los conflictos humanos", "Su contexto histórico", "Su lenguaje arcaico", "Su extensión"], correcta: 0 },
    { pregunta: "¿Qué aporta la ironía constante?", opciones: ["Múltiples niveles de lectura", "Una sola interpretación", "Neutralidad", "Mensaje moral fijo"], correcta: 0 },
    { pregunta: "¿Qué une profundamente a don Quijote y Sancho?", opciones: ["La bondad esencial", "La ambición", "La violencia", "La cobardía"], correcta: 0 },
    { pregunta: "¿Qué función cumple el contraste idealidad-realidad?", opciones: ["Sostener la estructura y el sentido", "Eliminar el humor", "Cerrar la narración", "Moralizar explícitamente"], correcta: 0 },
    { pregunta: "¿Qué demuestra la evolución de Sancho a lo largo de la obra?", opciones: ["Una progresiva complejidad del personaje", "Su inmovilismo", "Su degradación moral", "Su desaparición"], correcta: 0 },
    { pregunta: "¿Qué dimensión domina en la valoración final de El Quijote?", opciones: ["Humanista", "Religiosa", "Política", "Militar"], correcta: 0 },
    { pregunta: "¿Qué logra Cervantes para la narrativa posterior?", opciones: ["Sentar sus bases modernas", "Cerrar su evolución", "Limitar sus temas", "Uniformar estilos"], correcta: 0 },
    { pregunta: "¿Qué hace única la relación amo-escudero?", opciones: ["La influencia mutua", "La sumisión absoluta", "El antagonismo", "La indiferencia"], correcta: 0 },
    { pregunta: "¿Qué aporta el fracaso reiterado del protagonista?", opciones: ["Una dimensión trágico-cómica", "Un ritmo lento", "Un mensaje moral cerrado", "Una épica clásica"], correcta: 0 },
    { pregunta: "¿Qué tipo de héroe es finalmente don Quijote?", opciones: ["Un héroe humanizado", "Un héroe épico clásico", "Un antihéroe sin valores", "Un villano"], correcta: 0 },
    { pregunta: "¿Qué define el legado de El Quijote?", opciones: ["Su influencia duradera en la literatura", "Su éxito comercial puntual", "Su valor histórico local", "Su interés filológico"], correcta: 0 },
    { pregunta: "¿Qué papel cumple el lenguaje en la caracterización?", opciones: ["Define psicológica y socialmente a los personajes", "Es uniforme", "Es decorativo", "Es irrelevante"], correcta: 0 },
    { pregunta: "¿Qué relación hay entre forma y contenido?", opciones: ["La forma refuerza el sentido", "La forma es independiente", "La forma contradice el contenido", "No hay relación"], correcta: 0 },
    { pregunta: "¿Qué consigue Cervantes al cerrar definitivamente la historia?", opciones: ["Evitar continuaciones apócrifas", "Dejarla abierta", "Castigar al héroe", "Sorprender al lector"], correcta: 0 },
    { pregunta: "¿Qué tipo de risa propone El Quijote?", opciones: ["Reflexiva y crítica", "Cruel", "Intrascendente", "Trágica"], correcta: 0 },
    { pregunta: "¿Qué dimensión domina en don Quijote como símbolo?", opciones: ["La defensa del ideal frente a la realidad", "El poder político", "La sabiduría académica", "La victoria social"], correcta: 0 },
    { pregunta: "¿Qué explica la vigencia de la obra?", opciones: ["Su capacidad de múltiples interpretaciones", "Su contexto histórico", "Su lenguaje arcaico", "Su estructura episódica"], correcta: 0 },
    { pregunta: "¿Qué relación establece la obra con la tradición literaria?", opciones: ["La parodia y superación", "La imitación fiel", "El rechazo total", "La copia literal"], correcta: 0 },
    { pregunta: "¿Qué aporta la conciencia de fracaso al sentido global?", opciones: ["Profundidad humana", "Pesimismo absoluto", "Moral cerrada", "Didactismo"], correcta: 0 },
    { pregunta: "¿Qué logra Cervantes al combinar géneros en El Quijote?", opciones: ["Una obra abierta y compleja", "Confusión genérica", "Pérdida de unidad", "Un género cerrado"], correcta: 0 },
    { pregunta: "¿Qué tipo de modernidad encarna El Quijote?", opciones: ["Narrativa y perspectivística", "Política", "Científica", "Religiosa"], correcta: 0 },
    { pregunta: "¿Qué síntesis final ofrece la obra?", opciones: ["Tradición y modernidad", "Épica y tragedia", "Historia y mito", "Religión y moral"], correcta: 0 }
  ]
};