window.BibliotecaPreguntas = {
  fase0: [
    { pregunta: "¿Qué movimientos culturales se desarrollan en los siglos XVI y XVII en España?", opciones: ["Renacimiento y Barroco", "Humanismo y Romanticismo", "Clasicismo y Realismo", "Ilustración y Barroco"], correcta: 0 },
    { pregunta: "¿En qué siglo se sitúa principalmente el Renacimiento español?", opciones: ["Siglo XV", "Siglo XVI", "Siglo XVII", "Siglo XVIII"], correcta: 1 },
    { pregunta: "¿Qué corriente cultural inspira el Renacimiento?", opciones: ["La escolástica medieval", "El humanismo", "La Contrarreforma", "El racionalismo"], correcta: 1 },
    { pregunta: "¿Qué visión del mundo predomina en el Barroco?", opciones: ["Optimista y armónica", "Idealista y heroica", "Pesimista y desengañada", "Mítica y legendaria"], correcta: 2 },
    { pregunta: "¿Qué sentimiento se debilita a finales del siglo XVI según el texto?", opciones: ["La fe religiosa", "El optimismo renacentista", "El amor ideal", "La crítica social"], correcta: 1 },
    { pregunta: "¿Qué poeta representa el ideal del hombre renacentista?", opciones: ["Luis de Góngora", "Garcilaso de la Vega", "Francisco de Quevedo", "Fray Luis de León"], correcta: 1 },
    { pregunta: "¿Qué estrofa consolida Garcilaso en la lírica española?", opciones: ["La décima", "El romance", "El soneto", "La silva"], correcta: 2 },
    { pregunta: "¿Cuántos versos tiene un soneto?", opciones: ["12", "13", "14", "16"], correcta: 2 },
    { pregunta: "¿Qué tópico aparece con frecuencia en la poesía de Garcilaso?", opciones: ["Beatus ille", "Ubi sunt", "Carpe diem", "Locus amoenus"], correcta: 3 },
    { pregunta: "¿Qué género literario inaugura El Lazarillo de Tormes?", opciones: ["Novela pastoril", "Novela sentimental", "Novela picaresca", "Novela bizantina"], correcta: 2 }
  ],
  fase1: [
    { pregunta: "¿Qué emperador sirvió Garcilaso de la Vega?", opciones: ["Carlos I", "Felipe II", "Carlos V", "Fernando el Católico"], correcta: 0 },
    { pregunta: "¿Qué influencia extranjera es clave en la poesía de Garcilaso?", opciones: ["Francesa", "Italiana", "Inglesa", "Alemana"], correcta: 1 },
    { pregunta: "¿Qué poeta italiano inspira la lírica de Garcilaso?", opciones: ["Dante", "Boccaccio", "Petrarca", "Ariosto"], correcta: 2 },
    { pregunta: "¿Qué esquema métrico es habitual en el soneto?", opciones: ["ABAB ABAB CDC CDC", "ABBA ABBA CDC DCD", "AABB CCDD EEFF GG", "ABBA CDDC EFEF"], correcta: 1 },
    { pregunta: "¿Qué sentimiento domina en los sonetos de Garcilaso?", opciones: ["Heroísmo", "Humor", "Sentimientos amorosos", "Crítica social"], correcta: 2 },
    { pregunta: "¿Cuántos versos tiene la lira?", opciones: ["Cuatro", "Cinco", "Seis", "Siete"], correcta: 1 },
    { pregunta: "¿Qué combinación métrica caracteriza a la lira?", opciones: ["Octosílabos y endecasílabos", "Heptasílabos y endecasílabos", "Pentadecasílabos", "Solo endecasílabos"], correcta: 1 },
    { pregunta: "¿Qué tipo de expresión favorece la lira?", opciones: ["Épica y narrativa", "Burlesca y satírica", "Equilibrada y musical", "Violenta y exagerada"], correcta: 2 },
    { pregunta: "¿En qué ambiente se desarrollan las églogas de Garcilaso?", opciones: ["Urbano", "Cortesano", "Pastoril idealizado", "Mitológico exclusivamente"], correcta: 2 },
    { pregunta: "¿Qué personaje de la Égloga I representa el amor no correspondido?", opciones: ["Nemoroso", "Salicio", "Alcino", "Dafnis"], correcta: 1 },
    { pregunta: "¿Qué personaje sufre por la muerte de la amada en la Égloga I?", opciones: ["Salicio", "Nemoroso", "Tirreno", "Damón"], correcta: 1 },
    { pregunta: "¿Qué tópico literario aparece en la naturaleza de las églogas?", opciones: ["Beatus ille", "Tempus fugit", "Locus amoenus", "Ubi sunt"], correcta: 2 },
    { pregunta: "¿Qué égloga es la más extensa y compleja?", opciones: ["Égloga I", "Égloga II", "Égloga III", "Égloga IV"], correcta: 1 },
    { pregunta: "¿Dónde se sitúa la Égloga III?", opciones: ["Río Duero", "Río Tajo", "Río Ebro", "Río Guadalquivir"], correcta: 1 },
    { pregunta: "¿Qué figuras aparecen en la Égloga III?", opciones: ["Pastores", "Dioses olímpicos", "Ninfas", "Caballeros"], correcta: 2 },
    { pregunta: "¿En qué contexto religioso vive Fray Luis de León?", opciones: ["Reforma protestante", "Ilustración", "Contrarreforma", "Humanismo italiano"], correcta: 2 },
    { pregunta: "¿Qué experiencia vital influyó en Fray Luis de León?", opciones: ["El exilio", "El encarcelamiento por la Inquisición", "La guerra", "El viaje a Italia"], correcta: 1 },
    { pregunta: "¿Qué tópico destaca en la poesía de Fray Luis de León?", opciones: ["Carpe diem", "Beatus ille", "Ubi sunt", "Locus amoenus"], correcta: 1 },
    { pregunta: "¿Qué tema se opone a la vida mundana en Fray Luis?", opciones: ["La fama", "La vida retirada", "El heroísmo", "El amor cortés"], correcta: 1 },
    { pregunta: "¿Qué rasgo define el estilo de Fray Luis de León?", opciones: ["Oscuro y complejo", "Claro y sobrio", "Violento y satírico", "Exagerado y artificioso"], correcta: 1 }
  ],
  fase2: [
    { pregunta: "¿Qué movimiento literario se caracteriza por el desengaño?", opciones: ["Renacimiento", "Humanismo", "Barroco", "Clasicismo"], correcta: 2 },
    { pregunta: "¿Qué poeta es el máximo representante del culteranismo?", opciones: ["Quevedo", "Garcilaso", "Góngora", "Fray Luis"], correcta: 2 },
    { pregunta: "¿Qué sacerdote y poeta barroco escribió Las Soledades?", opciones: ["Quevedo", "Góngora", "Lope de Vega", "Cervantes"], correcta: 1 },
    { pregunta: "¿Cómo aparece el canon de belleza en Góngora?", opciones: ["Sencillo y natural", "Idealizado sin artificio", "Exagerado y artificioso", "Realista y crítico"], correcta: 2 },
    { pregunta: "¿Qué tópico se mantiene pero cambia de sentido en el Barroco?", opciones: ["Beatus ille", "Carpe diem", "Locus amoenus", "Ubi sunt"], correcta: 1 },
    { pregunta: "¿Qué poeta es el máximo exponente del conceptismo?", opciones: ["Góngora", "Garcilaso", "Quevedo", "Lope"], correcta: 2 },
    { pregunta: "¿Qué tópicos dominan en la poesía de Quevedo?", opciones: ["Carpe diem y locus amoenus", "Tempus fugit y ubi sunt", "Beatus ille y aurea mediocritas", "Amor cortés y honor"], correcta: 1 },
    { pregunta: "¿Qué visión del mundo muestra Quevedo?", opciones: ["Optimista", "Idealista", "Desengañada", "Heroica"], correcta: 2 },
    { pregunta: "¿En qué año se publica El Lazarillo de Tormes?", opciones: ["1504", "1527", "1554", "1605"], correcta: 2 },
    { pregunta: "¿Por qué es anónima la obra El Lazarillo de Tormes?", opciones: ["Por pérdida del autor", "Por modestia", "Por la crítica a instituciones", "Por tradición oral"], correcta: 2 },
    { pregunta: "¿Qué forma narrativa adopta El Lazarillo de Tormes?", opciones: ["Diálogo teatral", "Autobiografía ficticia", "Crónica histórica", "Relato epistolar real"], correcta: 1 },
    { pregunta: "¿Cómo se organiza la obra del Lazarillo?", opciones: ["Capítulos", "Libros", "Jornadas", "Tratados"], correcta: 3 },
    { pregunta: "¿Qué representa cada amo del Lazarillo?", opciones: ["Una virtud", "Un ideal literario", "Un vicio social", "Un valor religioso"], correcta: 2 },
    { pregunta: "¿Qué aprende Lázaro con el ciego?", opciones: ["La fe", "La obediencia", "La supervivencia mediante el engaño", "La cultura"], correcta: 2 },
    { pregunta: "¿Qué vicio encarna el clérigo?", opciones: ["Soberbia", "Hipocresía y avaricia", "Violencia", "Ignorancia"], correcta: 1 },
    { pregunta: "¿Qué critica el episodio del hidalgo?", opciones: ["La guerra", "La religión", "La honra basada en apariencias", "La nobleza hereditaria"], correcta: 2 },
    { pregunta: "¿Cuál es la finalidad principal del Lazarillo?", opciones: ["Entretener", "Idealizar la sociedad", "Denunciar una sociedad injusta", "Exaltar la nobleza"], correcta: 2 },
    { pregunta: "¿Qué acepta Lázaro al final de la obra?", opciones: ["La pobreza", "La soledad", "Una vida deshonrosa por estabilidad", "El castigo divino"], correcta: 2 },
    { pregunta: "¿Qué autor escribe Don Quijote de la Mancha?", opciones: ["Lope de Vega", "Cervantes", "Quevedo", "Góngora"], correcta: 1 },
    { pregunta: "¿En qué años se publican las dos partes del Quijote?", opciones: ["1595 y 1605", "1605 y 1615", "1610 y 1620", "1580 y 1590"], correcta: 1 },
    { pregunta: "¿Qué género parodia inicialmente el Quijote?", opciones: ["Novela pastoril", "Novela picaresca", "Libros de caballerías", "Novela bizantina"], correcta: 2 },
    { pregunta: "¿Cuántas salidas realiza don Quijote?", opciones: ["Dos", "Tres", "Cuatro", "Cinco"], correcta: 1 },
    { pregunta: "¿Quién encarna el sentido práctico en la novela?", opciones: ["Don Quijote", "Dulcinea", "Sancho Panza", "El ventero"], correcta: 2 },
    { pregunta: "¿Qué contraste es el eje central del Quijote?", opciones: ["Campo y ciudad", "Pasado y presente", "Ideal y realidad", "Fe y razón"], correcta: 2 },
    { pregunta: "¿Cómo trata Cervantes a su protagonista?", opciones: ["Lo ridiculiza sin matices", "Lo idealiza totalmente", "Combina locura y coherencia moral", "Lo presenta como villano"], correcta: 2 },
    { pregunta: "¿Qué obra reúne relatos breves de Cervantes?", opciones: ["La Galatea", "El Persiles", "Novelas ejemplares", "Viaje al Parnaso"], correcta: 2 },
    { pregunta: "¿Qué tipo de novela es El Persiles?", opciones: ["Picaresca", "Pastoril", "Bizantina", "Sentimental"], correcta: 2 },
    { pregunta: "¿Qué reflexiona Cervantes en Viaje al Parnaso?", opciones: ["La política", "La religión", "La poesía y los poetas", "La guerra"], correcta: 2 },
    { pregunta: "¿Qué rasgo define la narrativa cervantina?", opciones: ["Simplicidad estructural", "Complejidad psicológica", "Ausencia de diálogo", "Didactismo religioso"], correcta: 1 }
  ],
  fase3: [
    { pregunta: "¿Qué autor formula el Arte nuevo de hacer comedias?", opciones: ["Cervantes", "Calderón", "Lope de Vega", "Tirso de Molina"], correcta: 2 },
    { pregunta: "¿En qué año se publica el Arte nuevo?", opciones: ["1605", "1609", "1615", "1620"], correcta: 1 },
    { pregunta: "¿Qué modelo teatral crea Lope de Vega?", opciones: ["Tragedia clásica", "Comedia Nueva", "Auto sacramental", "Drama romántico"], correcta: 1 },
    { pregunta: "¿Qué mezcla defiende Lope en su teatro?", opciones: ["Prosa y verso", "Historia y mito", "Trágico y cómico", "Religión y política"], correcta: 2 },
    { pregunta: "¿Cuántos actos tiene la Comedia Nueva?", opciones: ["Dos", "Tres", "Cuatro", "Cinco"], correcta: 1 },
    { pregunta: "¿Qué estructura siguen los tres actos?", opciones: ["Inicio, nudo y desenlace", "Exposición, clímax y final", "Planteamiento, desarrollo y desenlace", "Presentación, conflicto y castigo"], correcta: 2 },
    { pregunta: "¿Qué unidad clásica mantiene Lope?", opciones: ["Tiempo", "Lugar", "Acción", "Personaje"], correcta: 2 },
    { pregunta: "¿Qué principio antepone Lope a las reglas clásicas?", opciones: ["La moral", "La tradición", "El gusto del público", "La enseñanza religiosa"], correcta: 2 },
    { pregunta: "¿Qué es el decoro poético?", opciones: ["El uso exclusivo del verso", "La adecuación del lenguaje al personaje", "La mezcla de géneros", "La unidad temática"], correcta: 1 },
    { pregunta: "¿Cómo hablan los personajes nobles?", opciones: ["Lenguaje vulgar", "Lenguaje cuidado y elevado", "Lenguaje humorístico", "Lenguaje técnico"], correcta: 1 },
    { pregunta: "¿Qué personaje utiliza lenguaje humorístico?", opciones: ["El rey", "El galán", "El gracioso", "El villano"], correcta: 2 },
    { pregunta: "¿Qué garantiza el decoro poético?", opciones: ["La originalidad", "La verosimilitud", "La sorpresa", "La musicalidad"], correcta: 1 },
    { pregunta: "¿Qué tres grandes temas dominan la Comedia Nueva?", opciones: ["Amor, honra y justicia", "Fe, razón y poder", "Guerra, política y religión", "Destino, muerte y tiempo"], correcta: 0 },
    { pregunta: "¿Qué es una comedia de honra?", opciones: ["Una obra burlesca", "Una obra centrada en el honor", "Una tragedia clásica", "Una sátira política"], correcta: 1 },
    { pregunta: "¿Qué tipo de obra combina amor y diferencia social?", opciones: ["Drama histórico", "Auto sacramental", "Comedia de enredo", "Tragedia"], correcta: 2 },
    { pregunta: "¿Qué personaje representa el poder legítimo?", opciones: ["El villano", "El gracioso", "El rey", "El poderoso injusto"], correcta: 2 },
    { pregunta: "¿Quién provoca el conflicto abusando de su autoridad?", opciones: ["El galán", "El rey", "El poderoso injusto", "El villano"], correcta: 2 },
    { pregunta: "¿Qué obra muestra una rebelión colectiva por la honra?", opciones: ["El perro del hortelano", "El caballero de Olmedo", "Fuenteovejuna", "La Galatea"], correcta: 2 },
    { pregunta: "¿Qué tipo de obra es El caballero de Olmedo?", opciones: ["Comedia de enredo", "Drama histórico", "Tragedia amorosa", "Auto sacramental"], correcta: 2 },
    { pregunta: "¿Qué conflicto predomina en El perro del hortelano?", opciones: ["Religioso", "Político", "Amoroso", "Bélico"], correcta: 2 },
    { pregunta: "¿Por qué triunfa el teatro de Lope?", opciones: ["Por su rigor clásico", "Por su brevedad", "Por adaptarse al público", "Por su exclusividad cortesana"], correcta: 2 },
    { pregunta: "¿En qué siglo se convierte el teatro en el género más popular?", opciones: ["XVI", "XVII", "XVIII", "XV"], correcta: 1 },
    { pregunta: "¿Qué evolución muestra la literatura del Renacimiento al Barroco?", opciones: ["De la fe al ateísmo", "De la armonía al desengaño", "De la épica al lirismo", "De lo popular a lo culto"], correcta: 1 },
    { pregunta: "¿Qué conciencia marca la literatura barroca?", opciones: ["La eternidad", "El progreso", "El paso del tiempo", "La naturaleza ideal"], correcta: 2 },
    { pregunta: "¿Qué no hace el Barroco respecto al Renacimiento?", opciones: ["Romper totalmente", "Reelaborar temas", "Cambiar significados", "Mantener formas"], correcta: 0 },
    { pregunta: "¿Qué autores fijan modelos fundamentales del Siglo de Oro?", opciones: ["Garcilaso, Cervantes y Lope", "Góngora, Quevedo y Calderón", "Fray Luis, Tirso y Lope", "Cervantes, Quevedo y Góngora"], correcta: 0 },
    { pregunta: "¿Cómo se concibe el amor en el Renacimiento?", opciones: ["Como pasión destructiva", "Como sentimiento noble", "Como engaño", "Como pecado"], correcta: 1 },
    { pregunta: "¿Qué visión del mundo ofrece el Barroco?", opciones: ["Ordenada y comprensible", "Idealizada", "Crítica y pesimista", "Heroica"], correcta: 2 },
    { pregunta: "¿Qué recurso expresivo usa el Barroco?", opciones: ["Sencillez extrema", "Contraste y exageración", "Neutralidad", "Minimalismo"], correcta: 1 },
    { pregunta: "¿Qué papel tiene la naturaleza en el Renacimiento?", opciones: ["Amenazante", "Caótica", "Idealizada", "Hostil"], correcta: 2 },
    { pregunta: "¿Qué refleja la literatura barroca?", opciones: ["Seguridad vital", "Desengaño y crisis", "Estabilidad social", "Optimismo político"], correcta: 1 },
    { pregunta: "¿Qué caracteriza la expresión renacentista?", opciones: ["Oscuridad", "Violencia verbal", "Claridad y equilibrio", "Ironía constante"], correcta: 2 },
    { pregunta: "¿Qué género inaugura Cervantes como moderno?", opciones: ["El teatro", "La lírica", "La novela", "El ensayo"], correcta: 2 },
    { pregunta: "¿Qué combinación logra Cervantes en el Quijote?", opciones: ["Épica y lírica", "Humor, crítica y reflexión", "Tragedia y mito", "Historia y religión"], correcta: 1 },
    { pregunta: "¿Qué aporta Lope de Vega al teatro?", opciones: ["Rigor clásico", "Un modelo nuevo y popular", "Teatro religioso exclusivo", "Teatro cortesano"], correcta: 1 },
    { pregunta: "¿Por qué son llamados Siglos de Oro?", opciones: ["Por la riqueza económica", "Por la expansión territorial", "Por el esplendor literario", "Por la estabilidad política"], correcta: 2 }
  ]
};